SPECIAL>LOADMODEL|"EPS.mdl"

SIMULATE>SAVELIST|OutputVarsToExport.lst
SIMULATE>RUNNAME|NoSettings
SIMULATE>READCIN|
MENU>RUN|O
MENU>VDF2TAB|NoSettings.vdfx|NoSettings.tsv|OutputVarsToExport.lst|+!||2021|2050|:NoSettings
FILE>DELETE|NoSettings.vdfx

SIMULATE>RUNNAME|100ces
SIMULATE>READCIN|100ces.cin
MENU>RUN|O
MENU>VDF2TAB|100ces.vdfx|100ces.tsv|OutputVarsToExport.lst|+!||2021|2050|:100ces
FILE>DELETE|100ces.vdfx

SIMULATE>SAVELIST|
